openapi: 3.0.1
info:
  title: KCrud
  version: '1.0'
servers: 
  - url: "https://localhost:7207/"
paths:
  /contact:
    get:
      tags:
        - Contact
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
    post:
      tags:
        - Contact
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
          text/json:
            schema:
              $ref: '#/components/schemas/Contact'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
  /contact/{id}:
    get:
      tags:
        - Contact
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Contact'
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
            text/json:
              schema:
                $ref: '#/components/schemas/Contact'
    put:
      tags:
        - Contact
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
          text/json:
            schema:
              $ref: '#/components/schemas/Contact'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
    delete:
      tags:
        - Contact
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
components:
  schemas:
    Contact:
      type: object
      properties:
        id:
          type: integer
          format: int32
        firstName:
          type: string
          nullable: true
        lastName:
          type: string
          nullable: true
        nickName:
          type: string
          nullable: true
        age:
          type: integer
          format: int32
        dateTimeCreated:
          type: string
          format: date-time
        isDeleted:
          type: boolean
      additionalProperties: false